apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS employee (
        id serial NOT NULL,
        name character varying(40) NOT NULL
    );

    INSERT INTO employee VALUES (2, 'Peter');
    INSERT INTO employee VALUES (4, 'Anna');
    INSERT INTO employee VALUES (8, 'Antonio');
