apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-claim0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/legion/Documents/kubernetes/codes_k8_deployments/v4_springBootDemo/postgres/docker-pg-vol/data"
