apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdemov1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootdemov1
  template:
    metadata:
      labels:
        app: springbootdemov1
    spec:
      containers:
       - image: dokcer3/springbootdemov1:1.0
         name: springbootdemov1
         ports:
           - containerPort: 8080
         env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/employeedb?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
