apiVersion: v1
kind: Service
metadata:
  name: springbootdemov1-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: springbootdemov1
  type: NodePort
